version: '3.8'
services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: PhpDockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
      -  ./api_map.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8000:80
  db:
    container_name: db-1
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mysqltest
        MYSQL_DATABASE: accounts
        MYSQL_USER: accounts_adm
        MYSQL_PASSWORD: accounts_test
    volumes:
      - ./dbs:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8007:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
